### ISSUE TITLE
Not real code

### ISSUE THREAD

**Issue by ghost** [TheArcticHusky/EpicGamerBot-Discord.js#15]
A function is not a real code use if statements or nothing at all.

**Comment by b1tcr4sh** [comment]
Python is not a real coding language.  It's created by the Chinese government to make people believe they are writing code, when really it mines Dogecoin in the background.

**Comment by b1tcr4sh** [comment]
Finished the app, implemented logic using many If statements, the app 1000% now works, thank you for the very helpful suggestion.  [Link to commit for reference](https://github.com/vividuwu/EpicGamerBot-Discord.js/commit/5c126f2528c2ad767dbaae811204174ff079922e)
